kind: PersistentVolume
apiVersion: v1 
metadata:
  name: mongodb-pv
  namespace: chatapp
  labels:
    app: mongo-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /data